steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Copy secure file from VM
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud compute scp \
          --zone=us-central1-a \
          --tunnel-through-iap \
          mounish@no-public-ip-vm:/home/mounish/secure-deps/app-config.json \
          ./app-config.json

  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/amjad-id-2/microservices-repo/my-app',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args:
      ['push', 'us-central1-docker.pkg.dev/amjad-id-2/microservices-repo/my-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Cloud Run
    args:
      [
        'run', 'deploy', 'my-secure-service',
        '--image', 'us-central1-docker.pkg.dev/amjad-id-2/microservices-repo/my-app',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/amjad-id-2/locations/us-central1/workerPools/mou-private-workr-pool

serviceAccount: projects/amjad-id-2/serviceAccounts/cloud-build-service@amjad-id-2.iam.gserviceaccount.com
